### ISSUE TITLE
wizard window doesn't respond

### ISSUE THREAD

**Issue by ErbB4** [Mighty-Data-Inc/dendritic-spine-counter#1]
Hi developers of dendritic spine counter,

I want to thank you for your efforts in developing this tool. I am very interested in applying it to my work. I am using it on my Windows machine. I found that even I used a relatively large detection window (100 pixels for instance), I could not tell if the function is running when I drew a path of dendrite. The window doesn't freeze, nor display any progress readout. So I am asking if there are any prerequisites on the hardware to use it? 32 or 64bit? Shall I use it on a Linux machine or a Mac OS system is preferred?

Thank you again and I hope you have a nice day.

Best regards,
Han

**Comment by omedalus** [comment]
Hello Han, and thank you for notifying us that you're having an issue. I'm so sorry to hear that it's not working properly on your computer. I will look into it this weekend.

The plug-in shouldn't be sensitive to your choice of platform. It was developed on Windows 10 (which is a 64-bit OS), with user-acceptance-testing being performed on a pretty recent build of MacOS.

My guess is that there's a problem somewhere with the Region-Of-Interest display. Dendritic Spine Counter uses ImageJ's ROI system to display the paths that it finds, so if that system isn't working for whatever reason, then it'll look like Dendritic Spine Counter isn't doing anything.

I'll try and examine it this weekend. Unfortunately, ImageJ plugins tend to be extremely sensitive to the specific nuances of an individual user's configuration, and problems tend to be very difficult to replicate. But I'll see what I can do.

 Could you please send me a sample image that you're trying to process, and perhaps a sample screenshot of Dendritic Spine Counter not doing anything? I know the latter request might seem silly, but I'm hoping that seeing a screenshot of your ImageJ instance might give me a clue about what might be going wrong.

Cheers
-Mikhail



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Han Lu ***@***.***>
Sent: Thursday, February 3, 2022, 7:51 AM
To: Mighty-Data-Inc/dendritic-spine-counter
Cc: Subscribed
Subject: [Mighty-Data-Inc/dendritic-spine-counter] wizard window doesn't respond (Issue #1)


Hi developers of dendritic spine counter,

I want to thank you for your efforts in developing this tool. I am very interested in applying it to my work. I am using it on my Windows machine. I found that even I used a relatively large detection window (100 pixels for instance), I could not tell if the function is running when I drew a path of dendrite. The window doesn't freeze, nor display any progress readout. So I am asking if there are any prerequisites on the hardware to use it? 32 or 64bit? Shall I use it on a Linux machine or a Mac OS system is preferred?

Thank you again and I hope you have a nice day.

Best regards,
Han

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMighty-Data-Inc%2Fdendritic-spine-counter%2Fissues%2F1&data=04%7C01%7C%7C29f5c0be5e224371f04808d9e713d5ae%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794894636748490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y0csSXURis5NYBbYZaD%2Bxz91dfzJ2CisG9qP%2F0Drhbo%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABJVJN7K72LHCIAKK3BZ5DUZJ23HANCNFSM5NO22C7A&data=04%7C01%7C%7C29f5c0be5e224371f04808d9e713d5ae%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794894636748490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qdmxxqvXSXLnUZbU2%2B3UzsQNROKx9mu9kH84BRCW55I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C29f5c0be5e224371f04808d9e713d5ae%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794894636748490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wj3tk9wNvEFXPEJ0sr6ySgDYjqk%2BT8FwmbEx9CEr1RQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C29f5c0be5e224371f04808d9e713d5ae%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637794894636748490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0iXmDDEkIA21uam%2B0nAEHTN0%2BZQ3FZO7kmMJGN007Qk%3D&reserved=0>.

**Comment by ErbB4** [comment]
Hi Mikhail,
I just tried it again and was about to take a screenshot/video for you. It works perfectly this time!! I think my PC was too full yesterday and I cleaned it in the evening so it works. It is a nice tool! I like it and I think it is even better than Imaris... would be great if spine head volume is also included in the future ;-)

Have a nice weekend!

Han

**Comment by omedalus** [comment]
Heh, very glad to hear it! I'm delighted that I can help you in your research. And thank you for the suggestion about spine head volume; I'll consult with my subject-matter expert and see if we can include it in a future release.
